version: '3'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./playbooks:/etc/asira/playbooks
      - ./logs:/app/logs
    environment:
      - ASIRA_DB_HOST=postgres
      - ASIRA_DB_PORT=5432
      - ASIRA_DB_USER=asira
      - ASIRA_DB_PASSWORD=asira_password
      - ASIRA_DB_NAME=asira
      - ASIRA_ES_HOSTS=http://elasticsearch:9200
      - ASIRA_REDIS_HOST=redis
      - ASIRA_RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - postgres
      - elasticsearch
      - redis
      - rabbitmq

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=asira
      - POSTGRES_PASSWORD=asira_password
      - POSTGRES_DB=asira
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  dashboard:
    build:
      context: .
      dockerfile: dashboard/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api

volumes:
  postgres_data:
  elasticsearch_data:
