# ASIRA Malware Containment Playbook
# Version: 1.0.0
# Last updated: 2025-03-15 12:34:22
# Author: Mritunjay-mj

id: pb_malware_containment
name: Malware Containment
description: Isolate and contain malware infection on endpoints and servers
execution_mode: sequential
enabled: true
version: 1.0.0
created_at: 1741784062
updated_at: 1741784062
author: Mritunjay-mj

actions:
  - id: isolate_host
    type: containment
    description: Isolate the infected host from the network
    command: edpt_control --isolate {incident.hostname} --reason "Malware containment for incident {incident.id}"
    continue_on_failure: false
    timeout: 120
    parameters:
      allow_security_tools: true
      block_internet: true
      block_intranet: true
      keep_security_connection: true

  - id: scan_host
    type: command
    description: Run a full antivirus scan on the infected host
    command: edpt_control --scan {incident.hostname} --full --priority high
    continue_on_failure: true
    timeout: 600
    parameters:
      scan_type: full
      scan_priority: high
      upload_results: true

  - id: collect_process_info
    type: enrichment
    description: Collect running processes and memory dump from the infected host
    command: edpt_forensic --processes {incident.hostname} --memory-dump --output {execution.id}_memory_dump
    continue_on_failure: true
    timeout: 300

  - id: collect_file_indicators
    type: enrichment
    description: Collect file hashes and indicators from the infected host
    command: edpt_forensic --files {incident.hostname} --hashes --output {execution.id}_file_indicators
    continue_on_failure: true
    timeout: 180

  - id: submit_to_sandbox
    type: api_call
    description: Submit suspicious files to sandbox for analysis
    api_endpoint: https://sandbox.example.com/api/submit
    api_method: POST
    api_payload:
      hostname: "{incident.hostname}"
      incident_id: "{incident.id}"
      files_path: "{action_results.collect_file_indicators.output_path}"
      priority: "high"
    continue_on_failure: true
    timeout: 180

  - id: block_iocs
    type: command
    description: Block identified indicators of compromise across the environment
    script: |
      #!/bin/bash
      # Extract IOCs from sandbox results
      python extract_iocs.py --input {action_results.submit_to_sandbox.results_file} --output iocs.txt
      # Block IOCs at the firewall and EDR levels
      edpt_control --block-iocs iocs.txt --scope enterprise
    continue_on_failure: true
    timeout: 300

  - id: update_threat_intelligence
    type: api_call
    description: Update threat intelligence platform with new IOCs
    api_endpoint: https://ti.example.com/api/iocs/batch
    api_method: POST
    api_payload:
      source: "ASIRA"
      confidence: "high"
      iocs_file: "{action_results.block_iocs.iocs_file}"
      reference: "Incident {incident.id}"
    continue_on_failure: true
    timeout: 60

  - id: notify_security_team
    type: notification
    description: Notify security team about the malware containment actions
    template: malware_incident
    channels:
      - email
      - slack
      - sms
    parameters:
      severity: "{incident.severity}"
      hostname: "{incident.hostname}"
      incident_id: "{incident.id}"
      malware_name: "{incident.malware_name}"
      ioc_count: "{action_results.block_iocs.ioc_count}"
      sandbox_report: "{action_results.submit_to_sandbox.report_url}"
    continue_on_failure: true
    timeout: 30

tags:
  - malware
  - endpoint
  - containment
  - infection
  - ransomware

target_severity:
  - medium
  - high
  - critical
